# Generated by Django 5.2.5 on 2025-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0002_masterorganization_masterparameter_mastersensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereadinglog',
            name='CHANNEL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicereadinglog',
            name='CHANNEL_CD',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicereadinglog',
            name='DEVICE_READING_LOG_VER',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
