# Generated by Django 5.2.5 on 2025-08-20 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0003_devicereadinglog_channel_devicereadinglog_channel_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_DATE',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_TIME',
            field=models.IntegerField(verbose_name=222746),
        ),
    ]
