# Generated by Django 5.2.5 on 2025-08-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0005_alter_devicereadinglog_reading_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_TIME',
            field=models.TimeField(),
        ),
    ]
