# Generated by Django 5.2.5 on 2025-08-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0006_alter_devicereadinglog_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmlog',
            name='ALARM_TIME',
            field=models.TimeField(),
        ),
    ]
