# Generated by Django 5.2.5 on 2025-08-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0007_alter_devicealarmlog_alarm_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmlog',
            name='ALARM_TIME',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_DATE',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_TIME',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
