# Generated by Django 5.2.5 on 2025-08-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0008_alter_devicealarmlog_alarm_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmlog',
            name='ALARM_DATE',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicealarmlog',
            name='ALARM_TIME',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
