# Generated by Django 5.2.5 on 2025-08-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0009_alter_devicealarmlog_alarm_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='CRT_DT',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='LST_UPD_DT',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
