# Generated by Django 5.2.5 on 2025-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0010_alter_devicereadinglog_crt_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='ORG_ID',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
