# Generated by Django 5.2.5 on 2025-08-25 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0011_alter_devicereadinglog_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='CRT_BY',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='CRT_DT',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='LST_UPD_BY',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='LST_UPD_DT',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='UNIT_ID',
            field=models.IntegerField(default=1),
        ),
    ]
