# Generated by Django 5.2.5 on 2025-08-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0012_alter_devicereadinglog_crt_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUOM',
            fields=[
                ('UOM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('UOM_NAME', models.CharField(max_length=200, unique=True)),
                ('UOM_STATUS', models.BooleanField(default=True)),
                ('CRT_DT', models.DateTimeField(auto_now_add=True)),
                ('CRT_BY', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
                'db_table': 'master_uom',
            },
        ),
    ]
