# Generated by Django 5.2.5 on 2025-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0013_masteruom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCentre',
            fields=[
                ('CENTRE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CENTRE_NAME', models.CharField(max_length=200)),
                ('CENTRE_STATUS', models.IntegerField()),
                ('CENTRE_STATUS_CD', models.IntegerField()),
                ('ORG_ID', models.IntegerField()),
                ('UNIT_ID', models.IntegerField()),
                ('CRT_DT', models.DateField(blank=True, null=True)),
                ('CRT_BY', models.IntegerField(blank=True, null=True)),
                ('LST_UPD_DT', models.DateField(blank=True, null=True)),
                ('LST_UPD_BY', models.IntegerField(blank=True, null=True)),
                ('MASTER_CENTRE_VER', models.TextField(blank=True, null=True)),
                ('CHANNEL', models.IntegerField(blank=True, null=True)),
                ('CHANNEL_CD', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
