# Generated by Django 5.2.5 on 2025-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0014_mastercentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicealarmlog',
            name='STATUS',
            field=models.CharField(default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicealarmlog',
            name='ALARM_DATE',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicealarmlog',
            name='NORMALIZED_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
