# Generated by Django 5.2.5 on 2025-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0015_devicealarmlog_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicealarmlog',
            name='STATUS',
        ),
        migrations.AlterField(
            model_name='devicealarmlog',
            name='ALARM_DATE',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicealarmlog',
            name='NORMALIZED_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
