# Generated by Django 5.2.5 on 2025-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0018_remove_devicealarmlog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicealarmlog',
            name='IS_ACTIVE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devicealarmlog',
            name='NORMALIZED_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
