# Generated by Django 5.2.5 on 2025-08-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0019_devicealarmlog_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicealarmlog',
            name='IS_ACTIVE',
        ),
        migrations.AlterField(
            model_name='devicealarmlog',
            name='NORMALIZED_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
