# Generated by Django 5.2.5 on 2025-08-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0020_remove_devicealarmlog_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicealarmlog',
            name='IS_ACTIVE',
            field=models.BooleanField(default=True),
        ),
    ]
