# Generated by Django 5.2.5 on 2025-08-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0021_devicealarmlog_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmlog',
            name='NORMALIZED_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
