# Generated by Django 5.2.5 on 2025-08-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0022_alter_devicealarmlog_normalized_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmlog',
            name='IS_ACTIVE',
            field=models.IntegerField(default=1),
        ),
    ]
