# Generated by Django 5.2.5 on 2025-08-28 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0023_alter_devicealarmlog_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicereadinglog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='CHANNEL',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='CHANNEL_CD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='CRT_BY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='LST_UPD_BY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='ORG_ID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_DATE',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_TIME',
            field=models.TimeField(verbose_name=datetime.time(11, 9, 49, 852065)),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='UNIT_ID',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='devicereadinglog',
            name='CRT_DT',
        ),
        migrations.RemoveField(
            model_name='devicereadinglog',
            name='DEVICE_READING_LOG_VER',
        ),
        migrations.RemoveField(
            model_name='devicereadinglog',
            name='LST_UPD_DT',
        ),
    ]
