# Generated by Django 5.2.5 on 2025-08-28 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0024_alter_devicereadinglog_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_DATE',
            field=models.DateField(verbose_name=datetime.date(2025, 8, 28)),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_TIME',
            field=models.TimeField(verbose_name=datetime.time(11, 23, 48, 727800)),
        ),
    ]
