# Generated by Django 5.2.5 on 2025-08-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0026_alter_devicereadinglog_reading_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='ORG_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='UNIT_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
