# Generated by Django 5.2.5 on 2025-08-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0027_alter_devicereadinglog_org_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='ORG_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
