# Generated by Django 5.2.5 on 2025-08-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0028_alter_devicereadinglog_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='UNIT_ID',
            field=models.IntegerField(default=1),
        ),
    ]
