# Generated by Django 5.2.5 on 2025-08-28 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0029_alter_devicereadinglog_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_TIME',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
