# Generated by Django 5.2.5 on 2025-08-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0030_alter_devicereadinglog_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmlog',
            name='ORG_ID',
            field=models.IntegerField(default=1),
        ),
    ]
