# Generated by Django 5.2.5 on 2025-08-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0031_alter_devicealarmlog_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_TIME',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
