# Generated by Django 5.2.5 on 2025-08-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0032_alter_devicereadinglog_reading_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicealarmlog',
            name='NORMALIZED_TIME',
        ),
    ]
