# Generated by Django 5.2.5 on 2025-08-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0033_remove_devicealarmlog_normalized_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicealarmlog',
            name='NORMALIZED_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
