# Generated by Django 5.2.5 on 2025-08-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0034_devicealarmlog_normalized_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercentre',
            name='CENTRE_STATUS',
            field=models.IntegerField(default=1),
        ),
    ]
