# Generated by Django 5.2.5 on 2025-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0035_alter_mastercentre_centre_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
