# Generated by Django 5.2.5 on 2025-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0037_alter_devicereadinglog_reading_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdevice',
            name='DEVICE_MACID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
