# Generated by Django 5.2.5 on 2025-08-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0038_masterdevice_device_macid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersensor',
            name='SENSOR_TYPE',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
