# Generated by Django 5.2.5 on 2025-09-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0039_alter_mastersensor_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmcalllog',
            name='ALARM_TIME',
            field=models.TimeField(),
        ),
    ]
