# Generated by Django 5.2.5 on 2025-09-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0040_alter_devicealarmcalllog_alarm_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmlog',
            name='EMAIL_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicealarmlog',
            name='SMS_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
