# Generated by Django 5.2.5 on 2025-09-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0041_alter_devicealarmlog_email_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdevice',
            name='CENTRE_ID',
            field=models.IntegerField(default=1),
        ),
    ]
