# Generated by Django 5.2.5 on 2025-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0042_masterdevice_centre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdevice',
            name='DEVICE_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
