# Generated by Django 5.2.5 on 2025-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0043_alter_masterdevice_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdevice',
            name='DEVICE_STATUS',
            field=models.IntegerField(default=1),
        ),
    ]
