# Generated by Django 5.2.5 on 2025-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0044_alter_masterdevice_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRole',
            fields=[
                ('ROLE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ROLE_NAME', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='compassdates',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='devicealarmcalllog',
            old_name='UNIT_ID',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='devicealarmcalllog',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='devicealarmlog',
            old_name='UNIT_ID',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='devicealarmlog',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='devicereadinglog',
            old_name='UNIT_ID',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='devicereadinglog',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='devicesensorlink',
            old_name='UNIT_ID',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='devicesensorlink',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='mastercentre',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='masterdevice',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='masterorganization',
            old_name='UNIT_ID',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='masterparameter',
            old_name='UNIT_ID',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='masterparameter',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='mastersensor',
            old_name='UNIT_ID',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='mastersensor',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='sensorparameterlink',
            old_name='UNIT_ID',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='sensorparameterlink',
            old_name='ORG_ID',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RemoveField(
            model_name='mastercentre',
            name='UNIT_ID',
        ),
        migrations.RemoveField(
            model_name='masterdevice',
            name='UNIT_ID',
        ),
        migrations.RemoveField(
            model_name='masterorganization',
            name='ORG_ID',
        ),
        migrations.AlterField(
            model_name='masterdevice',
            name='CENTRE_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='compassdates',
            unique_together={('ORGANIZATION_ID', 'BRANCH_ID')},
        ),
    ]
