# Generated by Django 5.2.5 on 2025-09-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0045_masterrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrole',
            name='ROLE_NAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='mastercentre',
            table='master_role',
        ),
    ]
