# Generated by Django 5.2.5 on 2025-09-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0046_alter_masterrole_role_name_alter_mastercentre_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mastercentre',
            table=None,
        ),
    ]
