# Generated by Django 5.2.5 on 2025-09-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0047_alter_mastercentre_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='seuser',
            name='ROLE_ID',
            field=models.IntegerField(null=True),
        ),
    ]
