# Generated by Django 5.2.5 on 2025-09-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0048_seuser_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicealarmlog',
            name='NORMALIZED_EMAIL_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicealarmlog',
            name='NORMALIZED_EMAIL_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicealarmlog',
            name='NORMALIZED_SMS_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicealarmlog',
            name='NORMALIZED_SMS_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
