# Generated by Django 5.2.5 on 2025-09-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0049_devicealarmlog_normalized_email_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercentre',
            name='CENTRE_STATUS_CD',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='masterdevice',
            name='DEVICE_STATUS_CD',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='masterorganization',
            name='ORGANIZATION_STATUS',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='masterorganization',
            name='ORGANIZATION_STATUS_CD',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='masterparameter',
            name='PARAMETER_STATUS',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='masterparameter',
            name='PARAMETER_STATUS_CD',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mastersensor',
            name='SENSOR_STATUS',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mastersensor',
            name='SENSOR_STATUS_CD',
            field=models.IntegerField(default=1),
        ),
    ]
