# Generated by Django 5.2.5 on 2025-09-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0050_alter_mastercentre_centre_status_cd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreOrganizationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORGANIZATION_ID', models.IntegerField()),
                ('CENTRE_ID', models.IntegerField()),
            ],
            options={
                'unique_together': {('ORGANIZATION_ID', 'CENTRE_ID')},
            },
        ),
    ]
