# Generated by Django 5.2.5 on 2025-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0051_centreorganizationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=50, unique=True)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('ACTUAL_NAME', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('CREATED_BY', models.IntegerField(blank=True, null=True)),
                ('CREATED_ON', models.DateTimeField(auto_now_add=True)),
                ('VALIDITY_START', models.DateField(blank=True, null=True)),
                ('VALIDITY_END', models.DateField(blank=True, null=True)),
                ('PASSWORD_RESET', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master_role',
            },
        ),
    ]
