# Generated by Django 5.2.5 on 2025-09-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0052_masteruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganizationCentreLink',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CENTRE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_api.mastercentre')),
                ('ORGANIZATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_api.masterorganization')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_api.masteruser')),
            ],
            options={
                'db_table': 'userorganizationcentrelink',
            },
        ),
    ]
