# Generated by Django 5.2.5 on 2025-09-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0053_userorganizationcentrelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='RE_CONFIRM_PASSWORD',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
