# Generated by Django 5.2.5 on 2025-09-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0054_masteruser_re_confirm_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masteruser',
            table='master_user',
        ),
    ]
