# Generated by Django 5.2.5 on 2025-09-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0055_alter_masteruser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteruser',
            name='RE_CONFIRM_PASSWORD',
        ),
    ]
