# Generated by Django 5.2.5 on 2025-09-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0056_remove_masteruser_re_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorganizationcentrelink',
            old_name='CENTRE',
            new_name='CENTRE_ID',
        ),
        migrations.RenameField(
            model_name='userorganizationcentrelink',
            old_name='ORGANIZATION',
            new_name='ORGANIZATION_ID',
        ),
        migrations.RenameField(
            model_name='userorganizationcentrelink',
            old_name='USER',
            new_name='USER_ID',
        ),
    ]
