# Generated by Django 5.2.5 on 2025-09-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0057_rename_centre_userorganizationcentrelink_centre_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorganizationcentrelink',
            old_name='ID',
            new_name='id',
        ),
    ]
