# Generated by Django 5.2.5 on 2025-09-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0058_rename_id_userorganizationcentrelink_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorganizationcentrelink',
            old_name='id',
            new_name='ID',
        ),
    ]
