# Generated by Django 5.2.5 on 2025-09-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0059_rename_id_userorganizationcentrelink_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorganizationcentrelink',
            name='ID',
        ),
        migrations.AddField(
            model_name='userorganizationcentrelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
