# Generated by Django 5.2.5 on 2025-09-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0060_remove_userorganizationcentrelink_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadinglog',
            name='CENTRE_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
