# Generated by Django 5.2.5 on 2025-09-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0061_alter_devicereadinglog_centre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereadinglog',
            name='CHANNEL',
        ),
        migrations.RemoveField(
            model_name='devicereadinglog',
            name='CHANNEL_CD',
        ),
        migrations.RemoveField(
            model_name='devicereadinglog',
            name='CRT_BY',
        ),
        migrations.RemoveField(
            model_name='devicereadinglog',
            name='LST_UPD_BY',
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='CENTRE_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='ORGANIZATION_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='READING_DATE',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicereadinglog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
