# Generated by Django 5.2.5 on 2025-09-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0062_remove_devicereadinglog_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='PHONE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='SEND_EMAIL',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='SEND_SMS',
            field=models.IntegerField(null=True),
        ),
    ]
