# Generated by Django 5.2.5 on 2025-09-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0063_masteruser_phone_masteruser_send_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAsterNotificationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORGANIZATION_ID', models.IntegerField()),
                ('NOTIFICATION_TIME', models.IntegerField(help_text='Notification time in seconds')),
            ],
            options={
                'db_table': 'master_notification_time',
            },
        ),
    ]
