# Generated by Django 5.2.5 on 2025-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0064_masternotificationtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('CATEGORY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CATEGORY_NAME', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'device_category',
            },
        ),
    ]
