# Generated by Django 5.2.5 on 2025-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0065_devicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdevice',
            name='CATEGORY_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
