# Generated by Django 5.2.5 on 2025-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0066_masterdevice_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='ROLE_ID',
            field=models.IntegerField(null=True),
        ),
    ]
